# version: '3.8'

services:
  # PostgreSQL сервис
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fsms_new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sgK2Jyx7
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      # LANG: C.UTF-8
      # LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres -d fsms_new" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

    # PHP приложение
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres # condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=fsms_new
      - DB_USERNAME=postgres
      - DB_PASSWORD=sgK2Jyx7
    command: >
      sh -c "
        until PGPASSWORD=sgK2Jyx7 pg_isready -h postgres -p 5432 -U postgres -d fsms_new -t 1; do
          echo 'Waiting for PostgreSQL...'
          sleep 2
        done &&
        php artisan migrate:fresh --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  postgres_data:
